version: "3.8"
name: gitea
services:
  prod:
    container_name: ${CONTAINER_NAME}
    image: "gitea/gitea:1.16.7"
    mem_limit: 4000m
    cpus: 4
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - ${APP_PORT}:3000
      - ${APP_SSH_PORT}:22
    volumes:
      - "./data:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./img:/data/gitea/public/img"
