version: "3.8"
services:
  prod:
    container_name: "gitea"
    image: "gitea/gitea:1.16.7"
    mem_limit: 4000m
    cpus: 4
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "8001:3000"
      - "5001:22"
    volumes:
      - "./data:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
